pypxe/dhcp.py: avoid exception when invoking export_leases
Fixes the following crash:

Traceback (most recent call last):

  [...]

  File "/usr/lib/python3.10/site-packages/pypxe/dhcp.py", line 145, in export_leases
    json.dump(export_safe, leases_file)
  File "/usr/lib/python3.10/json/__init__.py", line 180, in dump
    fp.write(chunk)
TypeError: a bytes-like object is required, not str